# Disable the "core" python plugins
disablePlugins:
  - lando-python

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/python": /home/runner/work/python/python

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev


